spring.application.name=ImageEditor
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
spring.datasource.url=jdbc:postgresql://localhost:5432/image-editor
spring.datasource.username=user1
spring.datasource.password=0880
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.thymeleaf.check-template-location=false

image-editor.app.jwt.secret=bt5uy86598p685tnu9gbh1
image-editor.app.jwt.expiration=2073600000